sudo: false
language: python
python:
  - "2.7"
  - "3.5"
branches:
  only:
    - master

install:
  - python setup.py install
  - pip install git+https://github.com/typesupply/defcon@ufo3
  - pip install git+https://github.com/behdad/fonttools
  - pip install git+https://github.com/unified-font-object/ufoLib

script:
  - for f in Lib/glyphsLib/*_test.py; do
  -   python "$f"
  -   if [[ "$?" -ne 0 ]]; then exit 1; fi
  - done
