sudo: false
language: python
python:
  - "2.7"
  - "3.5"
install:
  - python setup.py install
  - pip install git+https://github.com/typesupply/defcon
  - pip install git+https://github.com/behdad/fonttools
script:
  - for f in Lib/glyphsLib/*_test.py; do python "$f"; done
